=== Yoshino-s/yogame/src/json-schema/texture-schema.json
{
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "enum": [
        "yogame-texture"
      ]
    },
    "version": {
      "type": "string"
    },
    "metadata": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "cell": {
          "type": "number"
        },
        "img": {
          "type": "string"
        }
      },
      "required": [
        "cell",
        "id",
        "img"
      ]
    },
    "texture": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "x": {
            "type": "number"
          },
          "y": {
            "type": "number"
          },
          "width": {
            "type": "number"
          },
          "height": {
            "type": "number"
          }
        },
        "required": [
          "id",
          "x",
          "y"
        ]
      }
    }
  },
  "required": [
    "metadata",
    "texture",
    "type",
    "version"
  ],
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== Yoshino-s/yogame/assets/texture.ytx.json
{
  "type": "yogame-texture",
  "version": "v1.0.0",
  "metadata": {
    "id": "test",
    "cell": 16,
    "img": "/favicon.jpg"
  },
  "texture": [
    {
      "id": "t0",
      "x": 0,
      "y": 0
    },{
      "id": "t1",
      "x": 0,
      "y": 16
    },{
      "id": "t2",
      "x": 16,
      "y": 0
    },{
      "id": "t3",
      "x": 16,
      "y": 16
    }
  ]
}
